FROM python:3.9
WORKDIR /code
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONBUFFERED 1
COPY ./requirements.txt /code/requirements.txt
RUN apt-get update
RUN apt install -y libgl1-mesa-glx
RUN apt-get install -y python3-opencv poppler-utils
RUN pip3 install pdf2image
RUN pip3 install python-multipart
RUN pip3 install opencv-python
RUN pip3 install opencv-python-headless
RUN apt install libgl1-mesa-glx -y
RUN apt-get install 'ffmpeg'\
    'libsm6'\
    'libxext6'  -y
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./app /code/app
COPY ./bin /code/bin 
ADD ./files /code/files 
EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]